### ISSUE TITLE
Capture to image files does not work on Big Sur

### ISSUE THREAD

**Issue by banjun** [banjun/PhotoStudioPlayer#18]
## Steps to Reproduce

1. Connect to an iPhone (Devices -> iPhone)
2. Control -> Enable Captures
3. Control -> Capture Frame ([Enter])

## Expected Results

- Capture image files into capture folder (Documents/)

## Actual Results

- PhotoStudioPlayer does not capture any files
- Shows Console error

```
PhotoStudioPlayer	CMIO_Unit_Helpers_VTUtilities.cpp:1610:SetUpDecompressionOrTransferSession ### Err -12906
PhotoStudioPlayer	CMIO_Unit_Convertor_VideoToolboxDecompressor.cpp:949:rebuildVideoDecompressor [0x136146a00] Helpers::VTUtilities::SetUpDecompressionOrTransferSession() returned error -12906!
PhotoStudioPlayer	CMIO_Unit_Convertor_VideoToolboxDecompressor.cpp:1606:DoOneToOne [0x136146a00] EXCEPTION ON ERROR -12906
```

## Configurations

- Big Sur 11.0.1（20B29）
- Any versions of PhotoStudioPlayer 0.8.1, 0.9.0 (built with Xcode 11 on Catalina), or, 0.9.1 (build with Xcode 12.2 on Big Sur)

**Comment by xiaolouxinyue** [comment]
any progress？

**Comment by banjun** [comment]
no progress...

**Comment by banjun** [comment]
I've found a possible workaround.
@xiaolouxinyue Would you try capture with #23 ?
