### ISSUE TITLE
Option to fix the aspect ratio of the viewer?

### ISSUE THREAD

**Issue by charlie0129** [banjun/PhotoStudioPlayer#26]
Just like the QuickTime Player, when you open a video, no matter how you resize the window, the aspect ratio stays the same.

It will be helpful if there is an option to toggle this functionality, since currently the viewer is freely resizable, leaving blank edges (if the aspect ratio of the viewer and iPhone screen is not the same). Although it is not a big deal, a simple resize would solve it. Fixing the viewer aspect ratio to the iPhone screen would be better.

![Screen Shot 2022-04-02 at 7 34 01 PM](https://user-images.githubusercontent.com/55270174/161381361-bc6c03f7-951a-4867-9bb7-7a9cf6d5e6e7.png)

**Comment by banjun** [comment]
@charlie0129 Sounds good. What do you think about PR #25 ? Is the option (= enable/disable the feature that fixes aspect ratio) required for your purpose?

**Comment by charlie0129** [comment]
Yes, exactly. I compiled a version from that branch, and it worked well!

**Comment by banjun** [comment]
thank you for your test!
